hub: 'default' # 'default' to use the default server in bungeecord config
alreadyInHub: Már csatlakoztál ehhez a szerverhez!
disabledServersError: Ezt a parancsot itt nem használhatod
requiresPermission: false # Set to true to require the permission 'hubcommand.command' for executing /hub

disabled-servers: []

# Do not touch pls. Internal Use
config-version: 3