name: Build Plugin JAR

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'termurin'
          architecture: x64

      - name: Build jar
        run: mvn --batch-mode --update-snapshots verify

      - name: Archive build target
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
            target/*